# Data directory
DATA_ROOT: './data/'

# Model directory for grad-cam inference
MODEL_ROOT: './models/model_Resnet50_abnormal_axial_epoch_15.pth'

# Experimental Name & Camper ID
EXP_NAME: temp
CAMPER_ID: T6000

# Model: mrnet, resnet50
MODEL: 
  name: "mrnet"
  params: null

# Task & Plane
## Task: 'abnormal', 'acl', 'meniscus'
## Plane: 'axial', 'coronal', 'sagittal'
TASK: abnormal
PLANE: axial

epochs: 50
LR : 0.00001
BATCH_SIZE : 1
FOLD_NUM : 0 # 0 ~ 9

# optimizer : adam, adamw, rmsprop, lion
OPTIMIZER:
  name: "adam"
  params: 
    weight_decay : 0.1

# loss : cross_entropy, focal, iou, bce_focal, bce_iou
LOSS:
  name: "cross_entropy"
  params: null

# scheduler : step, cosine, plateau
SCHEDULER:
  name: "plateau"
  params: 
    patience : 3
    factor : .3
    threshold : 0.0001 
    verbose : True