# Data directory
DATA_ROOT: './data/'

MODEL_ROOT: './models/'

# Experimental Name & Camper ID
EXP_NAME: HR48AcSa
CAMPER_ID: T6106

# Model: mrnet, resnet50
MODEL: 
  name: "hrnet48"
  params: null

# Task & Plane
## Task: 'abnormal', 'acl', 'meniscus'
## Plane: 'axial', 'coronal', 'sagittal'
TASK: acl
PLANE: sagittal

epochs: 50
LR : 0.000001
BATCH_SIZE : 1
FOLD_NUM : 4 # 0 ~ 9

# optimizer : adam, adamw, rmsprop, lion
OPTIMIZER:
  name: "adam"
  params: 
    weight_decay : 0.1

# loss : cross_entropy, focal, iou, bce_focal, bce_iou
LOSS:
  name: "cross_entropy"
  params: null

# scheduler : step, cosine, plateau
SCHEDULER:
  name: ""
  params: 
    patience : 3
    factor : .3
    threshold : 0.0001 
    verbose : True