# Data directory
DATA_ROOT: './data/'

# Experimental Name
EXP_NAME: temp

# Task: 'abnormal', 'acl', 'meniscus'
TASK: abnormal

MODEL_PATH:
  axial: './models/model_abnormal_axial_best.pth'
  coronal: './models/model_abnormal_coronal_best.pth'
  sagittal: './models/model_abnormal_sagittal_best.pth'

FOLD_NUM: 4